question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.",
        "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

question = [{"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
             "question": "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
             "question": "The film &quot;2001: A Space Odyssey&quot; was released on December 31st, 2000.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
             "question": "The 2010 film &quot;The Social Network&quot; is a biographical drama film about MySpace founder Tom Anderson.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
             "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
             "question": "Shaquille O&#039;Neal appeared in the 1997 film &quot;Space Jam&quot;.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
             "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
             "question": "Samuel L. Jackson had the words, &#039;Bad Motherf*cker&#039; in-scripted on his lightsaber during the filming of Star Wars.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
             "question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
             "correct_answer": "False", "incorrect_answers": ["True"]},
            {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
             "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
             "correct_answer": "True", "incorrect_answers": ["False"]},
            {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
             "question": "Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.",
             "correct_answer": "False", "incorrect_answers": ["True"]}]
